steps:
- id: "Rodando docker-compose"
  name: 'docker/compose'
  args: ['-f', 'docker-compose.cloudbuild.yaml', 'up', '-d']

- id: "Chown in /var/www"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec','-u','root','-t','app','chown','-R','www-data:www-data','/var/www']

- id: "Rodando docker PS"
  name: 'docker'
  args: ['ps']

- id: "Rodando Composer"
  name: 'docker'
  args: ['exec', '-t', 'app', 'composer', 'install']

- id: "Copiando .env"
  name: 'docker'
  args: ['exec', '-t', 'app', 'cp', '.env.example', '.env']

- id: "Rodando key:generate"
  name: 'docker'
  args: ['exec', '-t', 'app', 'php', '/var/www/artisan', 'key:generate']

- id: "Rodando phpunit"
  name: 'docker'
  args: ['exec', '-t', 'app', 'php', '/var/www/vendor/bin/phpunit', '-c', '/var/www/phpunit.xml']
